"""Table: offline value-head selection before inference (crossing_criterion.py, random pairing, own-trajectory
labels on one held-out 1M sample). Reads planner_eval/crossing/<env>-1m-random-firstarrival.json and writes
tables/value_head_selection.tex + tables/numbers_vhsel.tex.

  python scripts/report_value_head_selection.py
"""
import json
import os
import sys

import numpy as np
from absl import app, flags

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paper_common import macro_key, tex_env  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FLAGS = flags.FLAGS
flags.DEFINE_string('envs', 'cube-double-play-v0,scene-play-v0,puzzle-4x4-play-v0,cube-triple-play-v0', '')
flags.DEFINE_string('crossing_dir', '/scratch/jwquan/wmpp/planner_eval/crossing', '')
flags.DEFINE_string('suffix', '-1m-random-firstarrival', 'result file suffix.')
flags.DEFINE_string('report', '/scratch/jwquan/wmpp/planner_eval/og50_final_sweep.json', 'report_og50 JSON (reported head per dataset).')
flags.DEFINE_string('out_dir', os.path.join(ROOT, 'WMPP_ICLR2027'), '')


def main(_):
    rep = {e['env_name']: e for e in json.load(open(FLAGS.report))}
    rows, macros, agree = [], [], 0
    for env in FLAGS.envs.split(','):
        d = json.load(open(os.path.join(FLAGS.crossing_dir, f'{env[:-3]}{FLAGS.suffix}.json')))
        r = d['results']['traj']
        dn = [k for k in r if k.startswith('direct/')]
        metric, direct = r['metric']['score'], float(np.mean([r[k]['score'] for k in dn]))
        dm = r['direct_minus_metric']
        sig = not (dm['lo'] <= 0 <= dm['hi'])
        picked = 'direct' if dm['delta'] > 0 else 'metric'
        reported = 'direct' if rep[env]['selected_variant'].startswith('critic') else 'metric'
        agree += int(picked == reported or not sig)
        star = '*' if sig else ''
        cell = lambda v, bold: (f'$\\mathbf{{{v:.2f}}}$' if bold else f'${v:.2f}$')
        rows.append(f"{tex_env(env)} & {cell(metric, picked == 'metric' and sig)} & {cell(direct, picked == 'direct' and sig)} & "
                    f"${dm['delta']:+.2f}$ [${dm['lo']:+.2f}$, ${dm['hi']:+.2f}$]{star} & {reported} \\\\")
        mk = macro_key(env)
        macros += [f'\\newcommand{{\\VhSelMetric{mk}}}{{{metric:.2f}}}', f'\\newcommand{{\\VhSelDirect{mk}}}{{{direct:.2f}}}',
                   f'\\newcommand{{\\VhSelDelta{mk}}}{{{dm["delta"]:+.2f}}}']
        print(f"{env[:-3]:22s} metric {metric:.3f} direct {direct:.3f} delta {dm['delta']:+.3f} [{dm['lo']:+.3f},{dm['hi']:+.3f}]{star}  picked {picked:6s} reported {reported}")
    tex = ('\\begin{tabular}{lccc c}\n\\toprule\n'
           'Dataset & metric & direct & direct $-$ metric [95\\% CI] & head in \\cref{tab:main} \\\\\n\\midrule\n'
           + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')
    macros += [f'\\newcommand{{\\VhSelNumEnvs}}{{{len(rows)}}}', f'\\newcommand{{\\VhSelNumAgree}}{{{agree}}}']
    os.makedirs(os.path.join(FLAGS.out_dir, 'tables'), exist_ok=True)
    open(os.path.join(FLAGS.out_dir, 'tables', 'value_head_selection.tex'), 'w').write(tex)
    open(os.path.join(FLAGS.out_dir, 'tables', 'numbers_vhsel.tex'), 'w').write('% Auto-generated by scripts/report_value_head_selection.py -- do not edit.\n' + '\n'.join(macros) + '\n')
    print('\n' + tex + '\n' + '\n'.join(macros))


if __name__ == '__main__':
    app.run(main)
